### ISSUE TITLE
ImportError: cannot import name uhd

### ISSUE THREAD

**Issue by letitbezh** [kit-cel/gr-drm#11]
when  i use drm_transmitter_gui.py  , it is wrong ,what should i do
```shell
founder@founder-pc:~/hackrf/gr-drm/apps/gui$ python drm_transmitter_gui.py 
Traceback (most recent call last):
  File "drm_transmitter_gui.py", line 13, in <module>
    import drm_transmitter
  File "/home/founder/hackrf/gr-drm/apps/gui/drm_transmitter.py", line 22, in <module>
    from gnuradio import uhd
ImportError: cannot import name uhd
```

**Comment by fwunsch** [comment]
This does not look like a gr-drm related problem. Make sure you installed UHD and set all the paths correctly so that it can be found at runtime.
